[package]
name = "ble-current-time-broadcaster"
version = "0.0.0"
edition = "2021"

[dependencies]
bluer = "0.13.3"
fastrand = "1.7.0"
tokio = { version = "1.17", features = ["macros", "rt", "signal"] }
